In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

In [2]:
df = pd.read_csv('C:\Mayura\Programming\Github_Projects\AI_ML_DL_Projects\Churn-Modelling\dataset\Churn_Modelling.csv')
df.head()

<>:1: SyntaxWarning: invalid escape sequence '\M'
<>:1: SyntaxWarning: invalid escape sequence '\M'
C:\Users\mayur\AppData\Local\Temp\ipykernel_9940\1784249948.py:1: SyntaxWarning: invalid escape sequence '\M'
  df = pd.read_csv('C:\Mayura\Programming\Github_Projects\AI_ML_DL_Projects\Churn-Modelling\dataset\Churn_Modelling.csv')


RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [3]:
df.drop(axis=1, columns=['RowNumber', 'CustomerId', 'Surname'], inplace=True)

In [4]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [5]:
le = LabelEncoder()
ohe = OneHotEncoder()

In [6]:
le.fit(df['Gender'])

LabelEncoder()

In [9]:
le.classes_

array(['Female', 'Male'], dtype=object)

In [10]:
le.transform(df.Gender)

array([0, 0, 0, ..., 0, 1, 0], shape=(10000,))

In [11]:
ohe.fit(df[['Geography']])

OneHotEncoder()

In [12]:
ohe.categories_

[array(['France', 'Germany', 'Spain'], dtype=object)]

In [13]:
ohe.transform(df[['Geography']]).toarray()

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       ...,
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]], shape=(10000, 3))

In [15]:
geo_df = pd.DataFrame(ohe.transform(df[['Geography']]).toarray(), columns=ohe.categories_[0])

In [16]:
geo_df.head()

France  Germany  Spain
0     1.0      0.0    0.0
1     0.0      0.0    1.0
2     1.0      0.0    0.0
3     1.0      0.0    0.0
4     0.0      0.0    1.0

In [18]:
le_df = pd.DataFrame(le.transform(df['Gender']))
le_df.head()

0
0  0
1  0
2  0
3  0
4  0

In [19]:
new_df = pd.concat([df, geo_df, le_df], axis=1)
new_df.head()

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619    France  Female   42       2       0.00              1   
1          608     Spain  Female   41       1   83807.86              1   
2          502    France  Female   42       8  159660.80              3   
3          699    France  Female   39       1       0.00              2   
4          850     Spain  Female   43       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary  Exited  France  Germany  Spain  \
0          1               1        101348.88       1     1.0      0.0    0.0   
1          0               1        112542.58       0     0.0      0.0    1.0   
2          1               0        113931.57       1     1.0      0.0    0.0   
3          0               0         93826.63       0     1.0      0.0    0.0   
4          1               1         79084.10       0     0.0      0.0    1.0   

   0  
0  0  
1  0  
2  0  
3  0  
4  0

In [20]:
new_df.drop(axis=1, columns=['Geography', 'Gender'], inplace=True)

In [21]:
new_df.head()

CreditScore  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0          619   42       2       0.00              1          1   
1          608   41       1   83807.86              1          0   
2          502   42       8  159660.80              3          1   
3          699   39       1       0.00              2          0   
4          850   43       2  125510.82              1          1   

   IsActiveMember  EstimatedSalary  Exited  France  Germany  Spain  0  
0               1        101348.88       1     1.0      0.0    0.0  0  
1               1        112542.58       0     0.0      0.0    1.0  0  
2               0        113931.57       1     1.0      0.0    0.0  0  
3               0         93826.63       0     1.0      0.0    0.0  0  
4               1         79084.10       0     0.0      0.0    1.0  0

In [24]:
new_df.rename(columns={0: 'Gender'}, inplace=True)
new_df.head()

CreditScore  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0          619   42       2       0.00              1          1   
1          608   41       1   83807.86              1          0   
2          502   42       8  159660.80              3          1   
3          699   39       1       0.00              2          0   
4          850   43       2  125510.82              1          1   

   IsActiveMember  EstimatedSalary  Exited  France  Germany  Spain  Gender  
0               1        101348.88       1     1.0      0.0    0.0       0  
1               1        112542.58       0     0.0      0.0    1.0       0  
2               0        113931.57       1     1.0      0.0    0.0       0  
3               0         93826.63       0     1.0      0.0    0.0       0  
4               1         79084.10       0     0.0      0.0    1.0       0

In [25]:
new_df.corr()

CreditScore       Age    Tenure   Balance  NumOfProducts  \
CreditScore         1.000000 -0.003965  0.000842  0.006268       0.012238   
Age                -0.003965  1.000000 -0.009997  0.028308      -0.030680   
Tenure              0.000842 -0.009997  1.000000 -0.012254       0.013444   
Balance             0.006268  0.028308 -0.012254  1.000000      -0.304180   
NumOfProducts       0.012238 -0.030680  0.013444 -0.304180       1.000000   
HasCrCard          -0.005458 -0.011721  0.022583 -0.014858       0.003183   
IsActiveMember      0.025651  0.085472 -0.028362 -0.010084       0.009612   
EstimatedSalary    -0.001384 -0.007201  0.007784  0.012797       0.014204   
Exited             -0.027094  0.285323 -0.014001  0.118533      -0.047820   
France             -0.008928 -0.039208 -0.002848 -0.231329       0.001230   
Germany             0.005538  0.046897 -0.000567  0.401110      -0.010419   
Spain               0.004780 -0.001685  0.003868 -0.134892       0.009039   
Gender             -0.002857 -0.027544  0.014733  0.012087      -0.021859   

                 HasCrCard  IsActiveMember  EstimatedSalary    Exited  \
CreditScore      -0.005458        0.025651        -0.001384 -0.027094   
Age              -0.011721        0.085472        -0.007201  0.285323   
Tenure            0.022583       -0.028362         0.007784 -0.014001   
Balance          -0.014858       -0.010084         0.012797  0.118533   
NumOfProducts     0.003183        0.009612         0.014204 -0.047820   
HasCrCard         1.000000       -0.011866        -0.009933 -0.007138   
IsActiveMember   -0.011866        1.000000        -0.011421 -0.156128   
EstimatedSalary  -0.009933       -0.011421         1.000000  0.012097   
Exited           -0.007138       -0.156128         0.012097  1.000000   
France            0.002467        0.003317        -0.003332 -0.104955   
Germany           0.010577       -0.020486         0.010297  0.173488   
Spain            -0.013480        0.016732        -0.006482 -0.052667   
Gender            0.005766        0.022544        -0.008112 -0.106512   

                   France   Germany     Spain    Gender  
CreditScore     -0.008928  0.005538  0.004780 -0.002857  
Age             -0.039208  0.046897 -0.001685 -0.027544  
Tenure          -0.002848 -0.000567  0.003868  0.014733  
Balance         -0.231329  0.401110 -0.134892  0.012087  
NumOfProducts    0.001230 -0.010419  0.009039 -0.021859  
HasCrCard        0.002467  0.010577 -0.013480  0.005766  
IsActiveMember   0.003317 -0.020486  0.016732  0.022544  
EstimatedSalary -0.003332  0.010297 -0.006482 -0.008112  
Exited          -0.104955  0.173488 -0.052667 -0.106512  
France           1.000000 -0.580359 -0.575418  0.006772  
Germany         -0.580359  1.000000 -0.332084 -0.024628  
Spain           -0.575418 -0.332084  1.000000  0.016889  
Gender           0.006772 -0.024628  0.016889  1.000000

In [ ]:
new_df.corr()[abs(new_df.corr()) > 0.1]['Exited'].sort_values(ascending=False).dropna()

Exited            1.000000
Age               0.285323
Germany           0.173488
Balance           0.118533
France           -0.104955
Gender           -0.106512
IsActiveMember   -0.156128
Name: Exited, dtype: float64

In [35]:
data_columns = new_df.corr()[abs(new_df.corr()) > 0.1]['Exited'].sort_values(ascending=False).dropna().index

In [67]:
data_columns

Index(['Exited', 'Age', 'Germany', 'Balance', 'France', 'Gender',
       'IsActiveMember'],
      dtype='object')

In [36]:
data = new_df[data_columns]
data.head()

Exited  Age  Germany    Balance  France  Gender  IsActiveMember
0       1   42      0.0       0.00     1.0       0               1
1       0   41      0.0   83807.86     0.0       0               1
2       1   42      0.0  159660.80     1.0       0               0
3       0   39      0.0       0.00     1.0       0               0
4       0   43      0.0  125510.82     0.0       0               1

In [37]:
data.reset_index(drop=True, inplace=True)

In [38]:
data.head()

Exited  Age  Germany    Balance  France  Gender  IsActiveMember
0       1   42      0.0       0.00     1.0       0               1
1       0   41      0.0   83807.86     0.0       0               1
2       1   42      0.0  159660.80     1.0       0               0
3       0   39      0.0       0.00     1.0       0               0
4       0   43      0.0  125510.82     0.0       0               1

In [39]:
data

Exited  Age  Germany    Balance  France  Gender  IsActiveMember
0          1   42      0.0       0.00     1.0       0               1
1          0   41      0.0   83807.86     0.0       0               1
2          1   42      0.0  159660.80     1.0       0               0
3          0   39      0.0       0.00     1.0       0               0
4          0   43      0.0  125510.82     0.0       0               1
...      ...  ...      ...        ...     ...     ...             ...
9995       0   39      0.0       0.00     1.0       1               0
9996       0   35      0.0   57369.61     1.0       1               1
9997       1   36      0.0       0.00     1.0       0               1
9998       1   42      1.0   75075.31     0.0       1               0
9999       0   28      0.0  130142.79     1.0       0               0

[10000 rows x 7 columns]

In [40]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [41]:
from sklearn.model_selection import train_test_split
X = data.drop(axis=1, columns=['Exited'])
y = data['Exited']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [42]:
X_train

Age  Germany    Balance  France  Gender  IsActiveMember
9254   32      0.0       0.00     1.0       1               1
1561   42      1.0  119624.60     0.0       1               1
1670   24      0.0  114739.92     0.0       1               0
6087   27      0.0  135637.00     1.0       0               0
6669   56      0.0  142147.32     1.0       1               0
...   ...      ...        ...     ...     ...             ...
5734   54      0.0   69712.74     1.0       1               1
5191   58      0.0       0.00     1.0       0               1
5390   38      0.0       0.00     1.0       0               0
860    43      0.0  190227.46     1.0       1               0
7270   51      1.0  147910.30     0.0       1               1

[8000 rows x 6 columns]

In [43]:
scaler.fit(X_train)
X_train = scaler.transform(X_train)

In [44]:
X_train

array([[-0.6557859 , -0.57946723, -1.21847056,  1.00150113,  0.91324755,
         0.97481699],
       [ 0.29493847,  1.72572313,  0.69683765, -0.99850112,  0.91324755,
         0.97481699],
       [-1.41636539, -0.57946723,  0.61862909, -0.99850112,  0.91324755,
        -1.02583358],
       ...,
       [-0.08535128, -0.57946723, -1.21847056,  1.00150113, -1.09499335,
        -1.02583358],
       [ 0.3900109 , -0.57946723,  1.8272593 ,  1.00150113,  0.91324755,
        -1.02583358],
       [ 1.15059039,  1.72572313,  1.1497197 , -0.99850112,  0.91324755,
         0.97481699]], shape=(8000, 6))

In [47]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix, auc, accuracy_score

In [46]:
model = LogisticRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

c:\Mayura\Programming\Github_Projects\AI_ML_DL_Projects\venv\Lib\site-packages\sklearn\utils\validation.py:2742: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  warnings.warn(


In [48]:
accuracy_score(y_test, y_pred)

0.1965

In [49]:
model.score(X_test, y_test)

c:\Mayura\Programming\Github_Projects\AI_ML_DL_Projects\venv\Lib\site-packages\sklearn\utils\validation.py:2742: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  warnings.warn(


0.1965

In [51]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00      1607
           1       0.20      1.00      0.33       393

    accuracy                           0.20      2000
   macro avg       0.10      0.50      0.16      2000
weighted avg       0.04      0.20      0.06      2000



c:\Mayura\Programming\Github_Projects\AI_ML_DL_Projects\venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Mayura\Programming\Github_Projects\AI_ML_DL_Projects\venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Mayura\Programming\Github_Projects\AI_ML_DL_Projects\venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavio

In [52]:
data.Exited.value_counts()

Exited
0    7963
1    2037
Name: count, dtype: int64

In [55]:
from imblearn.over_sampling import SMOTE
smote = SMOTE()
X_sm, y_sm = smote.fit_resample(X, y)

In [56]:
X_sm

Age   Germany        Balance    France  Gender  IsActiveMember
0       42  0.000000       0.000000  1.000000       0               1
1       41  0.000000   83807.860000  0.000000       0               1
2       42  0.000000  159660.800000  1.000000       0               0
3       39  0.000000       0.000000  1.000000       0               0
4       43  0.000000  125510.820000  0.000000       0               1
...    ...       ...            ...       ...     ...             ...
15921   45  0.126713  140471.685401  0.873287       0               0
15922   54  0.000000       0.000000  1.000000       1               0
15923   42  0.000000  145847.053512  0.000000       1               0
15924   66  0.000000  110752.531154  0.783954       0               0
15925   47  1.000000  106889.035852  0.000000       1               1

[15926 rows x 6 columns]

In [57]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [58]:
scaler.fit(X_train)
X_train = scaler.transform(X_train)

In [59]:
model = LogisticRegression()
model.fit(X_train, y_train)

LogisticRegression()

In [60]:
X_test = scaler.transform(X_test)
model.predict(X_test)

array([0, 0, 0, ..., 0, 0, 0], shape=(2000,))

In [61]:
y_pred = model.predict(X_test)
accuracy_score(y_test, y_pred)


0.8125

In [62]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.83      0.96      0.89      1607
           1       0.56      0.21      0.30       393

    accuracy                           0.81      2000
   macro avg       0.70      0.58      0.60      2000
weighted avg       0.78      0.81      0.78      2000



In [63]:
confusion_matrix(y_test, y_pred)

array([[1543,   64],
       [ 311,   82]])

In [ ]:
model_path = 'C:\Mayura\Programming\Github_Projects\AI_ML_DL_Projects\Churn-Modelling\Models\logistic_regression_model.pkl'
scaler_path = 'C:\Mayura\Programming\Github_Projects\AI_ML_DL_Projects\Churn-Modelling\Models\std_scaler.pkl'
le_path = 'C:\Mayura\Programming\Github_Projects\AI_ML_DL_Projects\Churn-Modelling\Models\label_encoder.pkl'
ohe_path = 'C:\Mayura\Programming\Github_Projects\AI_ML_DL_Projects\Churn-Modelling\Models\onehot_encoder.pkl'

<>:1: SyntaxWarning: invalid escape sequence '\M'
<>:2: SyntaxWarning: invalid escape sequence '\M'
<>:3: SyntaxWarning: invalid escape sequence '\M'
<>:4: SyntaxWarning: invalid escape sequence '\M'
<>:1: SyntaxWarning: invalid escape sequence '\M'
<>:2: SyntaxWarning: invalid escape sequence '\M'
<>:3: SyntaxWarning: invalid escape sequence '\M'
<>:4: SyntaxWarning: invalid escape sequence '\M'
C:\Users\mayur\AppData\Local\Temp\ipykernel_9940\403381193.py:1: SyntaxWarning: invalid escape sequence '\M'
  model_path = 'C:\Mayura\Programming\Github_Projects\AI_ML_DL_Projects\Models\logistic_regression_model.pkl'
C:\Users\mayur\AppData\Local\Temp\ipykernel_9940\403381193.py:2: SyntaxWarning: invalid escape sequence '\M'
  scaler_path = 'C:\Mayura\Programming\Github_Projects\AI_ML_DL_Projects\Models\std_scaler.pkl'
C:\Users\mayur\AppData\Local\Temp\ipykernel_9940\403381193.py:3: SyntaxWarning: invalid escape sequence '\M'
  le_path = 'C:\Mayura\Programming\Github_Projects\AI_ML_DL_Project

In [66]:
import pickle
pickle.dump(model, open(model_path, 'wb'))
pickle.dump(scaler, open(scaler_path, 'wb'))
pickle.dump(le, open(le_path, 'wb'))
pickle.dump(ohe, open(ohe_path, 'wb'))